### PR TITLE
qintelqwatch: New App - Initial Commit of the Qintel QWatch App

### PR DESCRIPTION
**Pull request by calvin-qintel**
#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [X] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [X] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
- [X] Limit your pull request to one application and submit multiple pull requests if necessary.
#### Please check the type of change your PR introduces:
- [X] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Release Notes (REQUIRED)
- Initial Release, providing the "search qwatch exposures" and "on poll" commands

## What is the current behavior? (OPTIONAL)
NA

## What is the new behavior? (OPTIONAL)
- New App

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by dhwanis-crest** [comment]
@calvin-qintel , Could you please provide me the access rights for this repo?

**Comment by calvin-qintel** [comment]
@dhwanis-crest I don't have access to change permissions on this repo. Pinging @pzhou-splunk who initially set it up.

**Comment by dhwanis-crest** [comment]
Hi @calvin-qintel , I need the access rights for this forked repo (qintel/splunk-soar-qintelqwatch) to push changes on this PR. I think this is created by you so you would’ve the permission to provide me the access.

**Comment by dhwanis-crest** [comment]
The changes of this PR are incorporated into  this- https://github.com/splunk-soar-connectors/qintelqwatch/pull/2

**Pull request merged**
